services:
  # Backend API (Development)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.dev
    container_name: pola-corp-backend-dev
    environment:
      NODE_ENV: development
      DATABASE_URL: ${DATABASE_URL}
      PORT: 3001
      FRONTEND_URL: http://localhost:3000
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - pola-corp-dev-network
    restart: unless-stopped
    command: npm run start:dev

  # Frontend Application (Development)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    container_name: pola-corp-frontend-dev
    environment:
      NUXT_PUBLIC_API_BASE_URL: http://localhost:3001/api
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - backend
    networks:
      - pola-corp-dev-network
    restart: unless-stopped
    command: npm run dev

networks:
  pola-corp-dev-network:
    driver: bridge
